"""user

Revision ID: 3bc922e379eb
Revises: e3bebc91773f
Create Date: 2026-07-07 16:13:04.378476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bc922e379eb'
down_revision: Union[str, Sequence[str], None] = 'e3bebc91773f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'male')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('male', mysql.INTEGER(), autoincrement=False, nullable=True, comment='是否为男性'))
    # ### end Alembic commands ###
