"""employee plugin

Revision ID: 527060d2aea5
Revises: cf8051be8969
Create Date: 2026-07-01 18:48:23.894360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '527060d2aea5'
down_revision: Union[str, Sequence[str], None] = 'cf8051be8969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'dwah')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('dwah', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
