"""employee plugin

Revision ID: cf8051be8969
Revises: 
Create Date: 2026-07-01 18:47:46.304629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf8051be8969'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('dwah', sa.String(length=100), nullable=True))
    op.alter_column('test_records', 'analyze_attach',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.JSON(),
               comment='分析附件（多文件路径数组）',
               existing_comment='分析附件',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_records', 'analyze_attach',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=500),
               comment='分析附件',
               existing_comment='分析附件（多文件路径数组）',
               existing_nullable=True)
    op.drop_column('employees', 'dwah')
    # ### end Alembic commands ###
